name: CI

on:
  push:
    branches:
      - draft
  pull_request:
    branches:
      - draft

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - uses: actions/checkout@v4

    - name: Build pdf
      run: make

    - name: Upload pdf
      uses: actions/upload-artifact@v3
      with:
        name: main
        path: build/*.pdf
        if-no-files-found: error